### ISSUE TITLE
Log transform in Powerlaw functions

### ISSUE THREAD

**Issue by henrikef** [threeML/astromodels#186]
Some of the [PL functions](https://github.com/threeML/astromodels/blob/master/astromodels/functions/functions_1D/powerlaws.py) have log10 transforms on the normalization (and cutoff energy if applicable) but some don't. 

E.g. `Super_cutoff_powerlaw` doesn't have it, `Cutoff_powerlaw` does. Is there any reason for this? I feel like either all normalizations should have the transform or none of them.

Any thoughts? It's an easy fix if we agree to add the transforms.

**Comment by grburgess** [comment]
@henrikef I think this was added with the idea that these help MLE find a solution quicker. I personally don't like the idea because MLE solution for the transform is not the same as the MLE solution without. But we should likely have them everywhere. 

In the astromodels config, you can turn them off:

```yaml
logging:
  developer: off
  startup_warnings: off
  warn_style: "blink medium_orchid"

modeling:
  use_parameter_transforms: false
  ignore_parameter_bounds: true

```

There is also a context manger:


```python
with turn_off_parameter_transforms():


```

There is also a slight speed up with them off.
